version: '3'
services:
  backend:
    build: ./apps/nestjs
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./apps/nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
 