version: '3'
services:
  backend:
    build:
      context: ./apps/nestjs
      dockerfile: Dockerfile
    ports:
      - "22:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./apps/nextjs
      dockerfile: Dockerfile
    ports:
      - "22:3001"
    environment:
      - NODE_ENV=production
 