version: '3'
services:
  backend:
    build:
      context: ./apps/nestjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  frontend:
    build:
      context: ./apps/nextjs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

 