name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build Docker image for the backend (NestJS)
      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend ./apps/nestjs
      
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy NestJS to Backend EC2 instance
      - name: Deploy NestJS to EC2 Backend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_BACKEND_IP }} << 'EOF'
            # Stop the current Docker container if running
            docker stop nestjs-backend || true
            docker rm nestjs-backend || true

            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest

            # Run the new container
            docker run -d -p 3000:3000 --name /nestjs-backend ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend:latest
          EOF

      
       # Build Docker image for the frontend (Next.js)
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend ./apps/nextjs

      # Deploy Next.js to Frontend EC2 instance
      - name: Deploy Next.js to EC2 Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_FRONTEND_IP }} << 'EOF'
            # Stop the current Docker container if running
            docker stop nextjs-frontend || true
            docker rm nextjs-frontend || true

            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest

            # Run the new container
            docker run -d -p 80:3000 --name nextjs-frontend ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest
          EOF